%%
% ISOLATE ge AND gi FROM MULTIPLE DENDRITIC DISTANCES
cd(fileparts(which(mfilename)));

gm = load('data\gm_baseline_low_freq.mat');
sece = load('data\sece_baseline_low_freq.mat');
seci = load('data\seci_baseline_low_freq.mat');

FILTP = [20 0.0001 3 0.92];
searchtime = [0.3 0.6];
gm_ge_corr_arr = zeros(1, size(gm.V, 1));
gm_gi_corr_arr = zeros(1, size(gm.V, 1));
sece_ge_corr_arr = zeros(1, size(gm.V, 1));
seci_gi_corr_arr = zeros(1, size(gm.V, 1));
gm_ge_norm_arr = zeros(1, size(gm.V, 1));
gm_gi_norm_arr = zeros(1, size(gm.V, 1));
sece_ge_norm_arr = zeros(1, size(gm.V, 1));
seci_gi_norm_arr = zeros(1, size(gm.V, 1));

start_idx = 80000
end_idx = 220000

for i = 1:size(gm.V, 1)
    i
    [ge,gi,VC,~] = ...
                  find_gegi(gm.V(i,1:end-1),...
                  gm.ac*1e-9,...
                  1/gm.dt,...
                  gm.reversals,...
                  searchtime,...
                  'FILTP', FILTP);

    gm_ge_corr = corrcoef(ge(start_idx:end_idx), gm.total_ge(start_idx:end_idx));
    gm_ge_corr_arr(i) = gm_ge_corr(1,2);
    gm_gi_corr = corrcoef(gi(start_idx:end_idx), gm.total_gi(start_idx:end_idx));
    gm_gi_corr_arr(i) = gm_gi_corr(1,2);
    sece_ge_corr = corrcoef(sece.g(i,start_idx:end_idx), gm.total_ge(start_idx:end_idx));
    sece_ge_corr_arr(i) = sece_ge_corr(1,2);
    seci_gi_corr = corrcoef(seci.g(i,start_idx:end_idx), gm.total_gi(start_idx:end_idx));
    seci_gi_corr_arr(i) = seci_gi_corr(1,2);

    gm_ge_norm = norm(ge(start_idx:end_idx) - gm.total_ge(start_idx:end_idx));
    gm_ge_norm_arr(i) = gm_ge_norm;
    gm_gi_norm = norm(gi(start_idx:end_idx) - gm.total_gi(start_idx:end_idx));
    gm_gi_norm_arr(i) = gm_gi_norm;
    sece_ge_norm = norm(sece.g(i,start_idx:end_idx) - gm.total_ge(start_idx:end_idx));
    sece_ge_norm_arr(i) = sece_ge_norm;
    seci_gi_norm = norm(seci.g(i,start_idx:end_idx) - gm.total_gi(start_idx:end_idx));
    seci_gi_norm_arr(i) = seci_gi_norm;

end

syn_dists = gm.syn_dists;
total_ge = gm.total_ge;
total_gi = gm.total_gi;

proximal_idx = 4;
dist_proximal = syn_dists(proximal_idx);
[ge,gi,VC,~] = ...
              find_gegi(gm.V(proximal_idx,1:end-1),...
              gm.ac*1e-9,...
              1/gm.dt,...
              gm.reversals,...
              searchtime,...
              'FILTP', FILTP);
gm_ge_proximal = ge;
gm_gi_proximal = gi;
gm_vc_proximal = VC;
sece_ge_proximal = sece.g(proximal_idx,:);
seci_gi_proximal = seci.g(proximal_idx,:);

distal_idx = 42;
dist_distal = syn_dists(distal_idx);
[ge,gi,VC,~] = ...
              find_gegi(gm.V(distal_idx,1:end-1),...
              gm.ac*1e-9,...
              1/gm.dt,...
              gm.reversals,...
              searchtime,...
              'FILTP', FILTP);
gm_ge_distal = ge;
gm_gi_distal = gi;
gm_vc_distal = VC;
sece_ge_distal = sece.g(distal_idx,:);
seci_gi_distal = seci.g(distal_idx,:);

save('corrcoef_batch_processed_baseline.mat', ...
    'total_ge', ...
    'total_gi', ...
    'syn_dists', ...
    'gm_ge_corr_arr', ...
    'gm_gi_corr_arr', ...
    'sece_ge_corr_arr', ...
    'seci_gi_corr_arr', ...
    'gm_ge_norm_arr', ...
    'gm_gi_norm_arr', ...
    'sece_ge_norm_arr', ...
    'seci_gi_norm_arr', ...
    'gm_ge_proximal', ...
    'gm_gi_proximal', ...
    'gm_vc_proximal', ...
    'sece_ge_proximal', ...
    'seci_gi_proximal', ...
    'dist_proximal', ...
    'gm_ge_distal', ...
    'gm_gi_distal', ...
    'gm_vc_distal', ...
    'sece_ge_distal', ...
    'seci_gi_distal', ...
    'dist_distal');
    
